services:
  nginx:
    container_name: nginx
    image: nginx:1.20-alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      - api

  api:
    container_name: api
    image: golang:latest
    ports:
      - ${GO_PORT}:8080
    volumes:
      - ./src/${PROJECT_NAME}:/go/src/app
    working_dir: /go/src/app
    tty: true
    environment:
      - TZ=${TZ}
    depends_on:
      - mysql
  
  cli:
    container_name: cli
    image: golang:latest
    volumes:
      - ./src/${CLI_PROJECT_NAME}:/go/src/app
    working_dir: /go/src/app
    tty: true
    environment:
      - TZ=${TZ}
    depends_on:
      - mysql
  
  mysql:
    container_name: mysql
    build: ./docker/mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${PROJECT_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-store:/data
  
  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - ${MINIO_ENDPOINT_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /export --console-address ":9001"
    volumes:
      - minio-store:/export
  
  opensearch:
    container_name: opensearch
    build:
      context: ./docker/opensearch
      dockerfile: Dockerfile
    ulimits:
      memlock:
        soft: ${OPENSEARCH_MEMLOCK_SOFT}
        hard: ${OPENSEARCH_MEMLOCK_HARD}
      nofile:
        soft: ${OPENSEARCH_NOFILE_SOFT}
        hard: ${OPENSEARCH_NOFILE_HARD}
    volumes:
      - opensearch-store:/usr/share/opensearch/data
    ports:
      - ${OPENSEARCH_REST_PORT}:9200
      - ${OPENSEARCH_PERFORMANCE_PORT}:9600
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}

  opensearch-dashboards:
    container_name: opensearch-dashboards
    image: opensearchproject/opensearch-dashboards:latest
    ports:
      - ${OPENSEARCH_DASHBOARDS_PORT}:5601
    expose:
      - ${OPENSEARCH_DASHBOARDS_PORT}
    environment:
      - OPENSEARCH_HOSTS=${OPENSEARCH_HOSTS}


volumes:
  mysql-store:
  redis-store:
  minio-store:
  opensearch-store:
